version: '3.8'

services:
  flask-backend:
    build: ./flask-server
    expose:
      - "5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./flask-server:/app
    depends_on:
      - linux_machine_1
      - linux_machine_2
    networks:
      - linux_net
    environment:
      - FLASK_ENV=development

  react-frontend:
    build: ./client
    depends_on:
      - flask-backend
    networks:
      - linux_net

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - flask-backend
      - react-frontend
    networks:
      - linux_net

  linux_machine_1:
    build: ./kali
    container_name: linux_machine_1
    stdin_open: true
    tty: true
    privileged: true
    command: sleep infinity

  linux_machine_2:
    build: ./kali
    container_name: linux_machine_2
    stdin_open: true
    tty: true
    privileged: true
    command: sleep infinity

networks:
  linux_net:
    driver: bridge
