version: '3.8'

services:
  flask-backend:
    build: ./flask-server
    container_name: flask-backend
    expose:
      - "5000"

  react-frontend:
    build: ./client
    container_name: react-frontend

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - flask-backend
      - react-frontend