version: "3.9"
services:
  flask-server:
    build: ./flask-server
    restart: always
    volumes:
      - ./data:/app/data
    networks:
      - backend

  nginx:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - flask-server
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend: